### ISSUE TITLE
Code Standards for WordPress VIP Go Environments

### ISSUE THREAD

**Issue by douglas-johnson** [prasidhda/woo-manage-fraud-orders#1]
Hello, thanks for making this plugin!

I am interested in using it on a site that is hosted on [WordPress VIP Go](https://wpvip.com/documentation/vip-go/).

The code we deploy to this service should meet their coding standard. The standard is available [here as a PHP Code Sniffer rule set](https://github.com/Automattic/VIP-Coding-Standards) and is described in more [human readable terms here](https://wpvip.com/documentation/vip-go/code-review-blockers-warnings-notices/).

Most of the additional rules are related to the running WordPress on containerized servers with caching at edge.

Would you be open to a pull request if I tried to apply this code standard?

**Comment by prasidhda** [comment]
Hello, 
Thanks for the interests in this plugin. 
I will be open to the pull request. Please feel free to make changes and send the pull request. 

Thanks.
