### ISSUE TITLE
Blacklist billing and shipping addresses

### ISSUE THREAD

**Issue by BrianHenryIE** [prasidhda/woo-manage-fraud-orders#12]
> = Can i add zipcode or city Address in the blacklist ? =
> No. Only Billing phone, email and IP address. Planning to add those features in next update.

I've written the code for this today. I'll make a PR soon once I've tested it properly.

--
You might be interested in a plugin I wrote, [Checkout Rate Limiter](https://github.com/BrianHenryIE/bh-wc-checkout-rate-limiter) which I think is complementary to yours.

**Comment by prasidhda** [comment]
HI @BrianHenryIE , 
Thanks for your contributions. I will be more than happy for your PR with this features. 
Thanks again.
