### ISSUE TITLE
Conflict with WooCommerce payment hook

### ISSUE THREAD

**Issue by develooperr** [prasidhda/woo-manage-fraud-orders#3]
Hi guys,

I installed and tested this plugin in development environment, everything is great! There just seems to be a problem. Sometimes the order status changes from Cancelled to Completed.

![image](https://user-images.githubusercontent.com/76970441/103574331-f2ec1400-4ee4-11eb-9d7f-84ec14ba6b7f.png)

I think I know the reason for this problem!

The `woocommerce_checkout_order_processed` hook operation works and works well.

The `woocommerce_checkout_order_processed` hook is in the process_checkout method of the `WC_Checkout` class in WooCommerce, right? This hook is inside `try / catch` and immediately after this hook, `process_order_payment` or `process_order_without_payment` methods are executed

![image](https://user-images.githubusercontent.com/76970441/103575210-9d186b80-4ee6-11eb-9170-e1baf4eda2ac.png)

It seems that in your plugin, when fraud is found, in order to get out of try and not enter the payment process,` throw Exception` must be executed, otherwise it will enter the payment process

If you look at the `WC_Order` class and the `payment_complete` method, the `woocommerce_valid_order_statuses_for_payment_complete` filter also has a `cancelled` status, so payment can be refilled and the status changed from "Cancelled" to "Completed".

![image](https://user-images.githubusercontent.com/76970441/103575347-cfc26400-4ee6-11eb-97c1-9b7ba20e8faa.png)

Can you check and talk about this?

**Comment by prasidhda** [comment]
@develooperr 
Would you please show me how to re-create the issue from user's perspective?

**Comment by develooperr** [comment]
@prasidhda Sure. Can you check this video please? I tried to show the problem quite clearly

https://user-images.githubusercontent.com/76970441/103621847-13e75000-4f4b-11eb-9d1b-8d284b812061.mp4

**Comment by prasidhda** [comment]
@develooperr 
Thanks for the video. 
Can you provide me the exact shop set up environment?

**Comment by develooperr** [comment]
@prasidhda I did not use any strange plugins. My test environment is on localhost. I used the "Woocommerce" and "Subscription" plugins, but the "Subscription" plugin is not necessary, and this problem also exists on a simple product. I used Braintree for the payment gateway, which I put the plugin link below:

https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/

You can follow the link below; Create a sandbox profile and perform the test.

https://sandbox.braintreegateway.com/login

Help : https://articles.braintreepayments.com/get-started/try-it-out

I also put the changes that need to be made in this comet, and it seems that apart from this problem, since the hook is inside try / catch, in case of an error, a "throw new Exception" must be created and "wc_add_notice" could not prevent the process from continuing.

https://github.com/prasidhda/woo-manage-fraud-orders/pull/4/commits/ae8f45259e53f6dae591833b399338fe8af4d1e3

Thanks

**Comment by prasidhda** [comment]
@develooperr 
Thanks for the detailed explanation of the issue. Your points about the issues are correct and applied fixes are valid too.
If possible, please create the pull request. 

Thanks.

**Comment by prasidhda** [comment]
Hi @develooperr ,
Thanks for trying out the plugin and and pointing the issue. 
This has been fixed in the following [commit](https://github.com/prasidhda/woo-manage-fraud-orders/commit/a962ccd3ca0d58ab6bb5673b672ccc4a2a340fc8).
